version: '3.7'

services:
  ninjas:
    build:
      context: .
      dockerfile: Dockerfile
    image: tretton-ninjas
    container_name: tretton-ninjas
    stdin_open: true # fixes the auto exit issue: <https://github.com/facebook/create-react-app/issues/8688>
    volumes:
      - '.:/app'
    environment:
      - DOCKER=true
      - NODE_ENV=production
    ports:
      - '80:80'