export const NINJAS_LIST_REQUEST = 'NINJAS_LIST_REQUEST';
export const NINJAS_LIST_REQUEST_SUCCESS = 'NINJAS_LIST_REQUEST_SUCCESS';
export const NINJAS_LIST_REQUEST_FAIL = 'NINJAS_LIST_REQUEST_FAIL';
